Feature/updateglobalsfile
SofiaHjerpe/unicorn-sokoban pull request #8
Opened 2024-03-14 13:44 UTC by SofiaHjerpe

Change globals file to globals.ts, convert GameArray into one array called GamePlans, modify types in App.tsx.

2024-03-14 16:07 UTC, Dakawe commented on sokoban/src/App.tsx
Du måste dela med newGameBoard[0] för få ut korrekt värde, (Den räknar längden på en row)
Det du ändrat till gör att den delar spelkartans height med kolumnvärdet istället.

2024-03-14 16:09 UTC, Dakawe commented on sokoban/src/Globals.ts
> -let GameBoard: any[] = [
Snyggt ihopbakat - lite input: hade du haft objekt så hade du kunnat ge fler värden (bananas namn, svårighet osv) som lätt kan nås för bruk senare.

2024-03-14 16:10 UTC, SofiaHjerpe commented on sokoban/src/App.tsx
>    const [value, setLevelValue] = useState("");
Ja jag behöver den för att sätta value på select i child komponenten.

2024-03-14 16:11 UTC, Dakawe requested changes
const style = { height: (500 / newGameBoard[0].length) * newGameBoard.length };

  const style = { height: (500 / newGameBoard.length) * newGameBoard.length };
  
  Den raden måste bytas pga annars kommer det bugga med storleken på rutor när banorna är ojämna x, y storlek

2024-03-14 16:11 UTC, SofiaHjerpe commented on sokoban/src/App.tsx
Oj tack! löser det :)

2024-03-14 16:19 UTC, Dakawe approved these changes

2024-03-14 16:29 UTC, judithorvathsv approved these changes

2024-03-15 09:21 UTC, Maichonok approved these changes

2024-03-15 11:00 UTC, merged